[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[unix_http_server]
file=/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisor.sock

[program:postgres]
command=/usr/lib/postgresql/16/bin/postgres -D %(ENV_PGDATA)s -c listen_addresses=127.0.0.1 -c unix_socket_directories=/var/run/postgresql
user=postgres
priority=10
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopsignal=INT
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:redis]
command=/usr/bin/redis-server --bind 127.0.0.1 --protected-mode yes --port 6379 --dir /var/lib/redis --appendonly yes --daemonize no
user=redis
priority=10
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:backend]
command=/usr/local/bin/start-backend.sh
directory=/opt/svix/backend
user=svix
priority=20
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopsignal=TERM
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:worker]
command=/usr/local/bin/wait-for-migrations.sh celery -A app.scheduler.celery_app:celery_app worker --loglevel=INFO
directory=/opt/svix/backend
user=svix
priority=30
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopsignal=TERM
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:beat]
command=/usr/local/bin/wait-for-migrations.sh celery -A app.scheduler.celery_app:celery_app beat --loglevel=INFO --schedule=/run/svix/celerybeat-schedule
directory=/opt/svix/backend
user=svix
priority=30
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopsignal=TERM
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
priority=40
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopsignal=QUIT
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
