import { FormEvent, useState } from 'react'
import { beginMfaSetup, finishMfaSetup, login, verifyMfa } from '../api/auth'

export function Login({ onAuthenticated }: { onAuthenticated: (token: string) => void }) {
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [temporaryToken, setTemporaryToken] = useState<string>(); const [code, setCode] = useState(''); const [provisioning, setProvisioning] = useState<string>(); const [error, setError] = useState('')
  const submitLogin = async (event: FormEvent) => { event.preventDefault(); setError(''); try { const state = await login(username, password); setTemporaryToken(state.temporary_token); if (state.mfa_setup_required) setProvisioning((await beginMfaSetup(state.temporary_token)).provisioning_uri) } catch { setError('用户名或密码不正确') } }
  const submitMfa = async (event: FormEvent) => { event.preventDefault(); if (!temporaryToken) return; setError(''); try { const result = provisioning ? await finishMfaSetup(temporaryToken, code) : await verifyMfa(temporaryToken, code); onAuthenticated(result.access_token) } catch { setError('验证码无效或已过期') } }
  if (temporaryToken) return <div className="login"><section><p className="eyebrow">TOTP MFA</p><h1>{provisioning ? '设置认证器' : '验证登录'}</h1>{provisioning && <><p>请将以下 URI 导入 Google Authenticator、Authy 或 Microsoft Authenticator：</p><code>{provisioning}</code></>}<form onSubmit={submitMfa}><input value={code} onChange={(event) => setCode(event.target.value)} inputMode="numeric" placeholder="6 位验证码" maxLength={6}/><button>继续</button></form>{error && <p className="error">{error}</p>}</section></div>
  return <div className="login"><section><p className="eyebrow">PRIVATE ANALYTICS</p><h1>Semi‑VIX</h1><p>所有行情与计算均为只读。</p><form onSubmit={submitLogin}><input value={username} onChange={(event) => setUsername(event.target.value)} placeholder="用户名"/><input value={password} onChange={(event) => setPassword(event.target.value)} type="password" placeholder="密码"/><button>登录</button></form>{error && <p className="error">{error}</p>}</section></div>
}
