import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { getSettings, saveSettings, getSystemStatus } from '../api/settings'
import { configureProvider, getProviderStatus, type ProviderName } from '../api/provider'
const symbols = ['SOXX', 'MU', 'SKHY', 'NVDA', 'AMD', 'AVGO']
export function Settings() {
  const query = useQuery({ queryKey: ['settings'], queryFn: getSettings }); const system = useQuery({ queryKey: ['system-status'], queryFn: getSystemStatus, refetchInterval: 10000 }); const provider = useQuery({ queryKey: ['provider-status'], queryFn: getProviderStatus, retry: false }); const client = useQueryClient()
  const save = useMutation({ mutationFn: saveSettings, onSuccess: () => client.invalidateQueries({ queryKey: ['settings'] }) }); const setProvider = useMutation({ mutationFn: (name: ProviderName) => configureProvider(name), onSuccess: () => client.invalidateQueries({ queryKey: ['provider-status'] }) }); const settings = query.data
  const toggle = (symbol: string) => settings && save.mutate({ ...settings, selected_symbols: settings.selected_symbols.includes(symbol) ? settings.selected_symbols.filter((item) => item !== symbol) : [...settings.selected_symbols, symbol] })
  return <main><header><div><p className="eyebrow">CONFIGURATION</p><h1>设置与系统状态</h1></div></header><section className="panel form"><h3>数据提供商</h3><label>提供商<select value={provider.data?.provider ?? 'IBKR'} onChange={(event) => setProvider.mutate(event.target.value as ProviderName)}><option value="IBKR">IBKR</option><option value="FUTU">Futu</option></select></label><p>连接状态：{provider.data?.connected ? '已连接' : provider.data?.configured ? '已配置，未连接' : '未配置'}</p></section><section className="panel form"><h3>计算设置</h3><label>刷新频率<select value={settings?.refresh_frequency_minutes ?? 15} onChange={(event) => settings && save.mutate({ ...settings, refresh_frequency_minutes: Number(event.target.value) })}><option value="5">5 分钟</option><option value="15">15 分钟</option><option value="30">30 分钟</option><option value="1440">每日</option></select></label><p>标的范围</p><div className="symbols">{symbols.map((symbol) => <label key={symbol}><input type="checkbox" checked={settings?.selected_symbols.includes(symbol) ?? false} onChange={() => toggle(symbol)}/> {symbol}</label>)}</div></section><section className="panel"><h3>系统状态</h3>{system.data && Object.entries(system.data).map(([key, value]) => <div className="status-row" key={key}><span>{key}</span><strong>{value ? String(value) : '—'}</strong></div>)}</section></main>
}
